# Generated by Django 3.2.23 on 2023-12-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtrip',
            name='locations',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomLocation',
        ),
    ]
