# Generated by Django 3.2.23 on 2023-12-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20231205_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlocation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customlocation',
            name='long',
            field=models.FloatField(),
        ),
    ]
