# Generated by Django 3.2.23 on 2023-12-13 04:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20231206_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtrip',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='customtrip',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
