# Generated by Django 3.2.23 on 2023-12-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_customtrip_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomLocation',
            new_name='Location',
        ),
    ]
