# Generated by Django 3.2.23 on 2023-12-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_trip_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order']},
        ),
    ]
