# Generated by Django 3.2.23 on 2023-12-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
